# 🚩 = Changed from default
# Orignal values and comments can be seen in dextool_template

[workarea]
root = "."
include = ["./src/*"]   # 🚩
exclude = []

[generic]
mutants = ["ror"]       # 🚩

[analyze]
include = ["./src/*"]   # 🚩
exclude = []
prune = true

[schema]
use = true
check_schemata = true

[coverage]
use = true

[database]
db = "dextool_mutate.sqlite3"

[compiler]
# ...

[compile_commands]
search_paths = ["./build/compile_commands.json"]

[mutant_test]
build_cmd = "./build.sh"                # 🚩
test_cmd = "./test.sh"                  # 🚩
analyze_using_builtin = ["ctest"]       # 🚩
detected_new_test_case = "resetAlive"
detected_dropped_test_case = "remove"
oldest_mutants = "test"
oldest_mutants_percentage = 1.0
use_early_stop = true
continues_check_test_suite = true
continues_check_test_suite_period = 100
max_mem_usage_percentage = 90.0

[report]
style = "plain"
sections = ["summary"]

[test_group]
# ...

[test]
# ...
